### ISSUE TITLE
available-versions issue

### ISSUE THREAD

**Issue by MaksymPrymierov** [MaksymPrymierov/mp_control#1]
Traceback (most recent call last):
  File "./mp_control.py", line 130, in <module>
    get_list_of_available_versions(config_object)
  File "./mp_control.py", line 68, in get_list_of_available_versions
    versions = os.listdir(spigot_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minecraft_spigot/test_project/spigot'

**Comment by MaksymPrymierov** [comment]
Fixed
